#
# Makefile for the DRIMe4 LCD Panel Manager drivers
#

obj-$(CONFIG_DRIME4_LCD_PANEL_MANAGER) += d4_lcd_panel_manager.o d4_lcd_panel_manager_ioctl.o
obj-$(CONFIG_DRIME4_LCD_PANEL_MANAGER) += d4_lcd_panel_manager_ctrl.o
obj-$(CONFIG_MAIN_LCD_1_SELECT) += mlcd_1_panel/
obj-$(CONFIG_MAIN_LCD_2_SELECT) += mlcd_2_panel/
obj-$(CONFIG_SUB_LCD_SELECT) += slcd_panel/
