#
# Makefile for the Bayer Engine module driver
#

#ccflags-y := -O0
ccflags-y := -O2

obj-$(CONFIG_DRIME4_BE) += d4_be.o
obj-$(CONFIG_DRIME4_BE) += d4_be_top.o
obj-$(CONFIG_DRIME4_BE) += d4_be_intr.o
obj-$(CONFIG_DRIME4_BE) += d4_be_ioctl.o

