#
# Makefile for the DRIMe4 Main LCD 1 Panels
#

obj-$(CONFIG_MLCD_1_PANEL_1) += lcd_vga_smd_3_0_panel.o
obj-$(CONFIG_MLCD_1_PANEL_2) += lcd_vga_auo_3_0_panel.o
obj-$(CONFIG_MLCD_1_PANEL_3) += lcd_wvga_smd_3_3_panel.o
obj-$(CONFIG_MLCD_1_PANEL_4) += lcd_wvga_smd_3_5_panel.o
obj-$(CONFIG_MLCD_1_PANEL_5) += lcd_xga_epson_evf_panel.o
obj-$(CONFIG_MLCD_1_PANEL_6) += lcd_xga_emagin_evf_panel.o
obj-$(CONFIG_MLCD_1_PANEL_7) += lcd_wvga_smd_3_69_panel.o
obj-$(CONFIG_MLCD_1_PANEL_8) += lcd_wvga_smd_3_3_panel_2.o
