#
# Makefile for the DSC drivers
#

obj-$(CONFIG_DRIME4_BMA) += bma/
obj-$(CONFIG_DRIME4_SMA) += sma/
obj-y += pp/
obj-$(CONFIG_DRIME4_MIPI) += mipi/
obj-$(CONFIG_DRIME4_IPCS) += ipcs/
obj-$(CONFIG_DRIME4_IPCM) += ipcm/
obj-y += ep/

obj-$(CONFIG_PMU_SELECT) += opener/
obj-$(CONFIG_DRIME4_BE) += be/
obj-$(CONFIG_DRIME4_SRP) += srp/
obj-$(CONFIG_DRIME4_BWM) += bwm/
obj-$(CONFIG_DRIME4_JPEG) += jpeg/
obj-$(CONFIG_DRIME4_JPEG_XR) += jxr/
obj-$(CONFIG_VIDEO_MFC5X) += mfc5x/
obj-$(CONFIG_DRIME4_CSM) += csm/