#
# Makefile for the DRIMe4 MIPI drivers
#

obj-$(CONFIG_DRIME4_MIPI) += d4_mipi.o
obj-$(CONFIG_DRIME4_MIPI) += d4_mipi_ioctl.o
obj-$(CONFIG_DRIME4_MIPI) += d4_mipi_ctrl_dd.o
obj-$(CONFIG_DRIME4_MIPI) += d4_mipi_dpc_pdma.o

