# DRIME4 platform support
snd-soc-drime4-objs := drime4-dma.o
snd-soc-drime4-i2s-objs := drime4-i2s.o

obj-$(CONFIG_SND_SOC_DRIME4) += snd-soc-drime4.o
obj-$(CONFIG_SND_DRIME4_I2S) += snd-soc-drime4-i2s.o

# DRIME4 Machine Support
snd-soc-drime4-wm8994-objs := drime4-wm8994.o
snd-soc-drime4-hdmi-objs := d4es-hdmi.o

obj-$(CONFIG_SND_SOC_D4_WM8994) += snd-soc-drime4-wm8994.o
obj-$(CONFIG_SND_SOC_D4_HDMI) += snd-soc-drime4-hdmi.o
obj-$(CONFIG_SND_SOC_D4_HDMI) += drime4-hdmi.o
