
#ifndef __CONFIG_KERNEL_H__
#define __CONFIG_KERNEL_H__

#define LINUX
#define PVR_BUILD_DIR "drime4_slp"
#define PVR_BUILD_DATE ""
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SGXCORE 540
#define SGX540
#define SUPPORT_SGX540
#define SUPPORT_SGX
#define SGX_CORE_REV 120
#define TRANSFER_QUEUE
#define PVR_SECURE_HANDLES
#define DISPLAY_CONTROLLER
#define RELEASE
#define SUPPORT_PERCONTEXT_PB
#define SUPPORT_HW_RECOVERY
#define SUPPORT_ACTIVE_POWER_MANAGEMENT
#define SUPPORT_SGX_HWPERF
#define SUPPORT_SGX_LOW_LATENCY_SCHEDULING
#define SUPPORT_SGX_NEW_STATUS_VALS
#define SUPPORT_DBGDRV_EVENT_OBJECTS
#define SYS_USING_INTERRUPTS
#define SUPPORT_LINUX_X86_WRITECOMBINE
#define SUPPORT_LINUX_X86_PAT
#define LDM_PLATFORM
#define DRIME4_SLP

/* for FHD test debugging */
#define PVRSRV_DUMP_MK_TRACE
#define PVRSRV_USSE_EDM_STATUS_DEBUG

#endif/*__CONFIG_KERNEL_H__*/
