#
# Makefile for the DRIMe4 DP drivers
#

obj-$(CONFIG_FB_DRIME4) += global_nodrm/ lcd_nodrm/

obj-$(CONFIG_DRM_DRIME4_DP_LCD) += global/
obj-$(CONFIG_DRM_DRIME4_DP_LCD) += lcd/
obj-$(CONFIG_DRIME4_LCD_PANEL_MANAGER) += lcd_panel_manager/
obj-$(CONFIG_DRM_DRIME4_DP_TV) += tv/
obj-$(CONFIG_DRM_DRIME4_DP_TV) += hdmi/
