#
# Makefile for the DRIMe4 IPCS drivers
#
obj-$(CONFIG_DRIME4_IPCS) += d4_ipcs.o
obj-$(CONFIG_DRIME4_IPCS) += d4_ipcs_ctrl.o
obj-$(CONFIG_DRIME4_IPCS) += d4_ipcs_intr_ctrl.o
obj-$(CONFIG_DRIME4_IPCS) += d4_ipcs_ioctl.o
