#
# Makefile for the DRIME4 framebuffer driver
#
ccflags-y := -O0

#obj-$(CONFIG_DRIME4_DP_TV)	+= d4_dp_tv.o
#obj-$(CONFIG_DRIME4_DP_TV) += d4_dp_tv_ioctl.o
obj-$(CONFIG_DRM_DRIME4_DP_TV) += d4_dp_tv_dd.o
