#
# Makefile for the DRIMe4 IPCM drivers
#

obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm.o
obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm_ctrl.o
#obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm_dma_set.o
#obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm_rsz_ctrl.o
obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm_intr.o
#obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm_core.o
#obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm_common_dd.o
#obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm_submodule.o
#obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm_md_ctrl.o
#obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm_ldcm.o
obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm_ioctl.o

# To use V4L2 Interface
#obj-$(CONFIG_DRIME4_IPCM) += d4-ipcm.o
#obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm_framework.o
#obj-$(CONFIG_DRIME4_IPCM) += d4_ipcm_v4l2.o
