#
# Makefile for kernel pwmdev drivers.
#
# small core, mostly translating board-specific
# config declarations into driver model code
obj-$(CONFIG_HT_PWM_CTRL)	+= d4_ht_pwm.o
obj-$(CONFIG_HT_PWM_UMODE)	+= pwmdev.o
